name: moorebtest
favicon: null
layout_spectrum: 0.048326846677809954
typography_spectrum: 0.16226325742900372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.026328913867473602
  lightness: 0.01639825850725174
  saturation: 0.46416146331466734
  rhythmicContrast: 0.5473470804281533
purpose: []
